---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - Sakura Ariga
  - Aliyah Maxine Ramos
  - Annie Yan
thanks: "Code and data are available at: LINK."
date: "`r Sys.time()`"
date-format: "D MMMM YYYY"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false
# Set up workspace 

install.packages("kableExtra")
install.packages("tidyverse")
install.packages("lessR")
install.packages("tidyr")
install.packages("reshape2")
install.packages("knitr")
install.packages("haven")
install.packages("vtable")

library(kableExtra)
library(tidyverse)
library(lessR)
library(tidyr)
library(reshape2)
library(knitr)
library(haven)
library(vtable)
```

```{r}
#| include: false
# Import cleaned data from the outputs folder, originally imported via the 01-download_data.R file
cleaned_2016gss_data <- read.csv(here::here("outputs/data/cleaned_2016gss_data.csv"))
```

# 1 Introduction

You can and should cross-reference sections and sub-sections. For instance, @sec-data and @sec-first-point.

# 2 Data {#sec-data}

```{r}
# Summary statistics of our GSS data 
summ_gss <- cleaned_2016gss_data %>% 
  select(`Age.Group`, `Sex`, `Race`, `Personal.Income`, `Total.Family.Income`, 
         `Highest.Education.Obtained`, `Number.of.Children`, `Marital.Status`,
         `Level.of.Happiness`, `Weekly.Total.of.Internet.Use..Hours.`)
# sumtable(summ_gss,  title = "Summary Statistics of Our Variables", out = "kable")
## the final line doesn't work for some reason and i'm mad
```

## 2.1 Survey

## 2.2 Questionnaire

# 3 Results

```{r}
#| label: fig-maritalandinternet
#| fig-cap: Weekly Total of Internet Use by Marital Status
#| echo: false
## Graph Marital Status VS. Internet Hours ##
mean_marital <- cleaned_2016gss_data %>%
  select(`Marital Status`,`Weekly Total of Internet Use (Hours)`) %>%
  group_by(`Marital Status`)%>%
  summarise(Mean_total = mean(`Weekly Total of Internet Use (Hours)` , na.rm=TRUE) )%>%
  pivot_wider(names_from = "Marital Status", values_from = c("Mean_total"))

## mutate from wide to long 
mean_marital <- melt(mean_marital)  #the function melt reshapes it from wide to long
mean_marital <- mean_marital[-6,]  # delete NA row

# save mean data
write_csv(mean_marital, "outputs/data/mean_marital.csv")

# use tidyverse-style code to pivot and summarise the data 
mean_marital |> ggplot(aes(x = variable, y = value)) + 
  geom_point() +
  theme(axis.text.x = element_text(angle = 45,hjust=1), 
        axis.line = element_line(colour = "black"),
        title = element_text(size = 12)) +
  labs(
    x = "Marital Status",
    y = "Internet Usage Hours"
  )
```


```{r}
#| label: fig-happyandinternet
#| fig-cap: Weekly Total of Internet Use by Level of Happiness
#| echo: false
## Graph Level of Happiness VS. Internet Hours##
mean_happy<- cleaned_2016gss_data %>%
  select(`Level of Happiness`,`Weekly Total of Internet Use (Hours)`) %>%
  group_by(`Level of Happiness`)%>%
  summarise(Mean_total = mean(`Weekly Total of Internet Use (Hours)` , na.rm=TRUE) )%>%
  pivot_wider(names_from = "Level of Happiness", values_from = c("Mean_total"))

## mutate from wide to long 
mean_happy <- melt(mean_happy)  #the function melt reshapes it from wide to long
mean_happy <- mean_happy[-4,]  # delete NA row

# save mean data
write_csv(mean_happy, "outputs/data/mean_happy.csv")

# use tidyverse-style code to pivot and summarise the data 
mean_happy |> ggplot(aes(x = variable, y = value)) + 
  geom_point() +
  theme(axis.text.x = element_text(angle = 45,hjust=1), 
        axis.line = element_line(colour = "black"),
        title = element_text(size = 12)) +
  labs(
    x = "Level of Happiness",
    y = "Internet Usage Hours"
  )
```


```{r}
#| label: fig-educandinternet
#| fig-cap: Weekly Total of Internet Use by Highest Education Obtained
#| echo: false
## Highest Education Obtained VS. Internet Hours ##
mean_edu<- cleaned_2016gss_data %>%
  select(`Highest Education Obtained`,`Weekly Total of Internet Use (Hours)`) %>%
  group_by(`Highest Education Obtained`)%>%
  summarise(Mean_total = mean(`Weekly Total of Internet Use (Hours)` , na.rm=TRUE) )%>%
  pivot_wider(names_from = "Highest Education Obtained", values_from = c("Mean_total"))

## mutate from wide to long 
mean_edu <- melt(mean_edu)  #the function melt reshapes it from wide to long
mean_edu <- mean_edu[-6,]  # delete NA row

# save mean data
write_csv(mean_edu, "outputs/data/mean_edu.csv")

# use tidyverse-style code to pivot and summarise the data 
mean_edu |> ggplot(aes(x = variable, y = value)) + 
  geom_point() +
  theme(axis.text.x = element_text(angle = 45,hjust=1), 
        axis.line = element_line(colour = "black"),
        title = element_text(size = 12)) +
  labs(
    x = "Highest Education Obtained",
    y = "Internet Usage Hours"
  )
```


# 4 Discussion

## 4.1 First discussion point {#sec-first-point}

## 4.2 Second discussion point

## 4.3 Third discussion point

## 4.4 Weaknesses and next steps

# 5 Appendix {.unnumbered}

# 6 Additional details

# 7 References
